import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SmartClass</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SmartClass</h1>

        <p className={styles.description}>Estructuras de Datos</p>

        <div className={styles.grid}>
          <Link href="/login">
            <a className={styles.card}>
              <h2>Login &rarr;</h2>
              <p>
                Inicie Sesión para poder usar las funcionalidades de SmartClass
              </p>
            </a>
          </Link>

          <Link href="/registro">
            <a className={styles.card}>
              <h2>Registro &rarr;</h2>
              <p>Regístrese en SmartClass para poder iniciar sesión</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Rodrigo Antonio Porón De León 201902781
      </footer>
    </div>
  );
}
